trigger:
- main

pool: OrionPool

stages:
  - stage: terraforminitoplan
    displayName: TerraformInitPlan
    jobs:
    - job: Terraforminstall
      # pool: OrionPool
      steps:
      - task: TerraformInstaller@1
        inputs:
          terraformVersion: 'latest'
